# Generated by Django 3.2.1 on 2022-08-06 16:55

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=sqlalchemy.sql.expression.true, null=sqlalchemy.sql.expression.true, upload_to='clientes_photos'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
    ]
